// swift-tools-version:5.9
// Flint Design System tokens for SwiftUI. Source: tokens.json; dist/swift/Flint.swift is generated by `npm run build`.
import PackageDescription

let package = Package(
  name: "Flint",
  platforms: [.iOS(.v16), .macOS(.v13)],
  products: [.library(name: "Flint", targets: ["Flint"])],
  targets: [.target(name: "Flint", path: "dist/swift")]
)
